SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720


ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 400
PLAYER_ACCELERATION = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5
SHOT_LIFESPAN = 2.0

PARTICLE_SIZE_RANGE = (1.0, 4.0)
PARTICLE_COUNT_RANGE = (4, 8)
PARTICLE_LIFE = 1.0

BOUNDRY_WIDTH = SCREEN_WIDTH + ASTEROID_MAX_RADIUS * 2
BOUNDRY_HEIGHT = SCREEN_HEIGHT + ASTEROID_MAX_RADIUS * 2

SOUND_GUN = "./fire.wav"
SOUND_THRUST = "./thrust.wav"
SOUND_SMALL_BOOM = "./bangSmall.wav"
SOUND_MEDIUM_BOOM = "./bangMedium.wav"
SOUND_LARGE_BOOM = "./bangLarge.wav"